### ISSUE TITLE
Mutating State

### ISSUE THREAD

**Issue by jlag34** [frbec/Jammming#2]
You have this code in your App.js -> addTrack method:

```
  addTrack (track) {
    let newState = this.state.savedTracks
    newState.push(track)
    this.setState({ savedTracks: newState })
  }
```

Here, you are trying to get a new copy of state but that won't work. `newState` is a direct reference to `this.state.savedTracks` meaning anything you do to one you do to the other. Instead you want a new copy by doing either of the following:

```
let newState = this.state.savedTracks.slice();
let newState = [ ...this.state.savedTracks ];
```

Either one will do the trick. Slice returns a new array, as does the spread operator.

**Comment by frbec** [comment]
This was a very valuable lesson, I had not realized that i was merely referencing the state. Thanks!
